import '../globals.css'
// import Login from "@/app/login/page";

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js'
}

export default function MainLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <>
            {children}
        </>
    )
}
